In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("/content/KaggleV2-May-2016.csv")

In [3]:
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [4]:
df.describe()

,PatientId,AppointmentID,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
count,1.105270e+05,1.105270e+05,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000
mean,1.474963e+14,5.675305e+06,37.088874,0.098266,0.197246,0.071865,0.030400,0.022248,0.321026
std,2.560949e+14,7.129575e+04,23.110205,0.297675,0.397921,0.258265,0.171686,0.161543,0.466873
min,3.921784e+04,5.030230e+06,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.172614e+12,5.640286e+06,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.173184e+13,5.680573e+06,37.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,9.439172e+13,5.725524e+06,55.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,9.999816e+14,5.790484e+06,115.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000

In [5]:
df.describe

<bound method NDFrame.describe of            PatientId  AppointmentID Gender          ScheduledDay  \
0       2.987250e+13        5642903      F  2016-04-29T18:38:08Z
1       5.589978e+14        5642503      M  2016-04-29T16:08:27Z
2       4.262962e+12        5642549      F  2016-04-29T16:19:04Z
3       8.679512e+11        5642828      F  2016-04-29T17:29:31Z
4       8.841186e+12        5642494      F  2016-04-29T16:07:23Z
...              ...            ...    ...                   ...
110522  2.572134e+12        5651768      F  2016-05-03T09:15:35Z
110523  3.596266e+12        5650093      F  2016-05-03T07:27:33Z
110524  1.557663e+13        5630692      F  2016-04-27T16:03:52Z
110525  9.213493e+13        5630323      F  2016-04-27T15:09:23Z
110526  3.775115e+14        5629448      F  2016-04-27T13:30:56Z

              AppointmentDay  Age      Neighbourhood  Scholarship  \
0       2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0
1       2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0
2       2016-04-29T00:00:00Z   62      MATA DA PRAIA            0
3       2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0
4       2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0
...                      ...  ...                ...          ...
110522  2016-06-07T00:00:00Z   56        MARIA ORTIZ            0
110523  2016-06-07T00:00:00Z   51        MARIA ORTIZ            0
110524  2016-06-07T00:00:00Z   21        MARIA ORTIZ            0
110525  2016-06-07T00:00:00Z   38        MARIA ORTIZ            0
110526  2016-06-07T00:00:00Z   54        MARIA ORTIZ            0

        Hipertension  Diabetes  Alcoholism  Handcap  SMS_received No-show
0                  1         0           0        0             0      No
1                  0         0           0        0             0      No
2                  0         0           0        0             0      No
3                  0         0           0        0             0      No
4                  1         1           0        0             0      No
...              ...       ...         ...      ...           ...     ...
110522             0         0           0        0             1      No
110523             0         0           0        0             1      No
110524             0         0           0        0             1      No
110525             0         0           0        0             1      No
110526             0         0           0        0             1      No

[110527 rows x 14 columns]>

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  object
 4   AppointmentDay  110527 non-null  object
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB

In [7]:
#lets check the totla rows and columns
print("Total rows",df.shape[0])
print("Total columns",df.shape[1])

Total rows 110527
Total columns 14

In [8]:
# lets check the columns names
print("Columns",df.columns)

Columns Index(['PatientId', 'AppointmentID', 'Gender', 'ScheduledDay',
       'AppointmentDay', 'Age', 'Neighbourhood', 'Scholarship', 'Hipertension',
       'Diabetes', 'Alcoholism', 'Handcap', 'SMS_received', 'No-show'],
      dtype='object')

In [9]:
# lets check the data types
df.dtypes

PatientId         float64
AppointmentID       int64
Gender             object
ScheduledDay       object
AppointmentDay     object
Age                 int64
Neighbourhood      object
Scholarship         int64
Hipertension        int64
Diabetes            int64
Alcoholism          int64
Handcap             int64
SMS_received        int64
No-show            object
dtype: object

In [10]:
## lets check if there are missing values
df.isnull().sum()

PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

## Exploratory Data Analysis

In [13]:
## out of all the patients , lets check the unique ones
print("Unique Patients",df["PatientId"].nunique())

Unique Patients 62299

In [14]:
# lets check for unique appointments
print("Unique appintments",df["AppointmentID"].nunique())

Unique appintments 110527

In [15]:
# lets checke the values of no show
df["No-show"].value_counts()

No-show
No     88208
Yes    22319
Name: count, dtype: int64

In [16]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [20]:
# we observe that the columns names are in caps , so lets standardize them making it lowercase with no spaces
df.columns=df.columns.str.lower().str.replace(" ","_")

In [21]:
df.head()

,patientid,appointmentid,gender,scheduledday,appointmentday,age,neighbourhood,scholarship,hipertension,diabetes,alcoholism,handcap,sms_received,no-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [23]:
#lets check if there are duplicates
df.duplicated().sum()

np.int64(0)

In [24]:
# there were no duplicates
# now lets check the statistics side of it
df.describe()

,patientid,appointmentid,age,scholarship,hipertension,diabetes,alcoholism,handcap,sms_received
count,1.105270e+05,1.105270e+05,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000
mean,1.474963e+14,5.675305e+06,37.088874,0.098266,0.197246,0.071865,0.030400,0.022248,0.321026
std,2.560949e+14,7.129575e+04,23.110205,0.297675,0.397921,0.258265,0.171686,0.161543,0.466873
min,3.921784e+04,5.030230e+06,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.172614e+12,5.640286e+06,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.173184e+13,5.680573e+06,37.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,9.439172e+13,5.725524e+06,55.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,9.999816e+14,5.790484e+06,115.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000

There is an avg values of -1 in age which is practically impossible , so lets fix it

In [28]:
len(df[df['age'] == -1 ])

1

##DATA CLEANINIG

In [29]:
df.drop((df.index[df["age"]==-1]),inplace=True)
len(df[df["age"]==-1])

0

In [30]:
df.head(2)

,patientid,appointmentid,gender,scheduledday,appointmentday,age,neighbourhood,scholarship,hipertension,diabetes,alcoholism,handcap,sms_received,no-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No

In [31]:
#lets fix the spellings and standardize the column name
df.rename(columns={"hipertension":"hypertension","no-show":"no_show"},inplace=True)

In [32]:
df.head(1)

,patientid,appointmentid,gender,scheduledday,appointmentday,age,neighbourhood,scholarship,hypertension,diabetes,alcoholism,handcap,sms_received,no_show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No

In [34]:
#duplicates
df.duplicated(subset=['patientid','no_show']).sum()

np.int64(38710)

In [35]:
# remove the status if there are duplicates in status and id
df.drop_duplicates(subset=['patientid','no_show'],inplace=True)

In [36]:
# lets check now if there are duplicates for the saem
df.duplicated(subset=['patientid','no_show']).sum()

np.int64(0)

In [37]:
df

,patientid,appointmentid,gender,scheduledday,appointmentday,age,neighbourhood,scholarship,hypertension,diabetes,alcoholism,handcap,sms_received,no_show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110518,7.263315e+13,5630375,F,2016-04-27T15:15:06Z,2016-06-07T00:00:00Z,50,MARIA ORTIZ,0,0,0,0,0,1,No
110520,9.969977e+14,5650534,F,2016-05-03T07:51:47Z,2016-06-07T00:00:00Z,42,MARIA ORTIZ,0,0,0,0,0,1,No
110521,3.635534e+13,5651072,F,2016-05-03T08:23:40Z,2016-06-07T00:00:00Z,53,MARIA ORTIZ,0,0,0,0,0,1,No
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No

In [38]:
#changing the dtypes for analysis
df["patientid"] = df["patientid"].astype(str)
df["appointmentid"] = df["appointmentid"].astype(str)

In [40]:
df.dtypes

patientid         object
appointmentid     object
gender            object
scheduledday      object
appointmentday    object
age                int64
neighbourhood     object
scholarship        int64
hypertension       int64
diabetes           int64
alcoholism         int64
handcap            int64
sms_received       int64
no_show           object
dtype: object

In [41]:
# we see that the schedule daya and appointment day are in onject format we gotto change that to datetime
df["scheduledday"]=pd.to_datetime(df["scheduledday"])
df["appointmentday"]=pd.to_datetime(df["appointmentday"])

In [43]:
df.info()

<bound method DataFrame.info of                 patientid appointmentid gender              scheduledday  \
0        29872499824296.0       5642903      F 2016-04-29 18:38:08+00:00
1       558997776694438.0       5642503      M 2016-04-29 16:08:27+00:00
2         4262962299951.0       5642549      F 2016-04-29 16:19:04+00:00
3          867951213174.0       5642828      F 2016-04-29 17:29:31+00:00
4         8841186448183.0       5642494      F 2016-04-29 16:07:23+00:00
...                   ...           ...    ...                       ...
110518   72633149253362.0       5630375      F 2016-04-27 15:15:06+00:00
110520  996997666245785.0       5650534      F 2016-05-03 07:51:47+00:00
110521   36355337746436.0       5651072      F 2016-05-03 08:23:40+00:00
110522    2572134369293.0       5651768      F 2016-05-03 09:15:35+00:00
110524   15576631729893.0       5630692      F 2016-04-27 16:03:52+00:00

                  appointmentday  age      neighbourhood  scholarship  \
0      2016-04-29 00:00:00+00:00   62    JARDIM DA PENHA            0
1      2016-04-29 00:00:00+00:00   56    JARDIM DA PENHA            0
2      2016-04-29 00:00:00+00:00   62      MATA DA PRAIA            0
3      2016-04-29 00:00:00+00:00    8  PONTAL DE CAMBURI            0
4      2016-04-29 00:00:00+00:00   56    JARDIM DA PENHA            0
...                          ...  ...                ...          ...
110518 2016-06-07 00:00:00+00:00   50        MARIA ORTIZ            0
110520 2016-06-07 00:00:00+00:00   42        MARIA ORTIZ            0
110521 2016-06-07 00:00:00+00:00   53        MARIA ORTIZ            0
110522 2016-06-07 00:00:00+00:00   56        MARIA ORTIZ            0
110524 2016-06-07 00:00:00+00:00   21        MARIA ORTIZ            0

        hypertension  diabetes  alcoholism  handcap  sms_received no_show
0                  1         0           0        0             0      No
1                  0         0           0        0             0      No
2                  0         0           0        0             0      No
3                  0         0           0        0             0      No
4                  1         1           0        0             0      No
...              ...       ...         ...      ...           ...     ...
110518             0         0           0        0             1      No
110520             0         0           0        0             1      No
110521             0         0           0        0             1      No
110522             0         0           0        0             1      No
110524             0         0           0        0             1      No

[71816 rows x 14 columns]>

<class 'pandas.core.frame.DataFrame'>
Index: 71816 entries, 0 to 110524
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patientid       71816 non-null  object
 1   appointmentid   71816 non-null  object
 2   gender          71816 non-null  object
 3   scheduledday    71816 non-null  datetime64[ns, UTC]
 4   appointmentday  71816 non-null  datetime64[ns, UTC]
 5   age             71816 non-null  int64
 6   neighbourhood   71816 non-null  object
 7   scholarship     71816 non-null  int64
 8   hypertension    71816 non-null  int64
 9   diabetes        71816 non-null  int64
 10  alcoholism      71816 non-null  int64
 11  handcap         71816 non-null  int64
 12  sms_received    71816 non-null  int64
 13  no_show         71816 non-null  object
dtypes: datetime64[ns, UTC](2), int64(7), object(5)
memory usage: 10.2+ MB

In [44]:
df

,patientid,appointmentid,gender,scheduledday,appointmentday,age,neighbourhood,scholarship,hypertension,diabetes,alcoholism,handcap,sms_received,no_show
0,29872499824296.0,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,558997776694438.0,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4262962299951.0,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,867951213174.0,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8841186448183.0,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110518,72633149253362.0,5630375,F,2016-04-27 15:15:06+00:00,2016-06-07 00:00:00+00:00,50,MARIA ORTIZ,0,0,0,0,0,1,No
110520,996997666245785.0,5650534,F,2016-05-03 07:51:47+00:00,2016-06-07 00:00:00+00:00,42,MARIA ORTIZ,0,0,0,0,0,1,No
110521,36355337746436.0,5651072,F,2016-05-03 08:23:40+00:00,2016-06-07 00:00:00+00:00,53,MARIA ORTIZ,0,0,0,0,0,1,No
110522,2572134369293.0,5651768,F,2016-05-03 09:15:35+00:00,2016-06-07 00:00:00+00:00,56,MARIA ORTIZ,0,0,0,0,0,1,No
110524,15576631729893.0,5630692,F,2016-04-27 16:03:52+00:00,2016-06-07 00:00:00+00:00,21,MARIA ORTIZ,0,0,0,0,0,1,No

In [47]:
# since we are dealing with appointments lets check the lead time , which means the duration between the appointment and when it takes place
# since we are dealing with appointments lets check the lead time , which means the duration between the appointment and when it takes place
df["lead_time"]=(pd.to_datetime(df['appointmentday'])-pd.to_datetime(df['scheduledday'])).dt.days

In [48]:
df["lead_time"]

0         -1
1         -1
2         -1
3         -1
4         -1
          ..
110518    40
110520    34
110521    34
110522    34
110524    40
Name: lead_time, Length: 71816, dtype: int64

In [49]:
# we see that there are negative time, which is impossible so lets clean it
df[df["lead_time"]<0]

,patientid,appointmentid,gender,scheduledday,appointmentday,age,neighbourhood,scholarship,hypertension,diabetes,alcoholism,handcap,sms_received,no_show,lead_time
0,29872499824296.0,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,No,-1
1,558997776694438.0,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,No,-1
2,4262962299951.0,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,No,-1
3,867951213174.0,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,-1
4,8841186448183.0,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,No,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110495,7499488949126.0,5759838,M,2016-06-01 13:49:47+00:00,2016-06-01 00:00:00+00:00,40,MARIA ORTIZ,0,0,0,0,0,0,No,-1
110501,454425189389.0,5758133,M,2016-06-01 10:19:12+00:00,2016-06-01 00:00:00+00:00,44,MARIA ORTIZ,0,0,0,0,0,0,No,-1
110511,823599626588.0,5786742,F,2016-06-08 08:50:20+00:00,2016-06-08 00:00:00+00:00,14,MARIA ORTIZ,0,0,0,0,0,0,No,-1
110512,98762456447375.0,5786368,F,2016-06-08 08:20:01+00:00,2016-06-08 00:00:00+00:00,41,MARIA ORTIZ,0,0,0,0,0,0,No,-1
110513,86747784995281.0,5785964,M,2016-06-08 07:52:55+00:00,2016-06-08 00:00:00+00:00,2,ANTÔNIO HONÓRIO,0,0,0,0,0,0,No,-1

In [50]:
df=df[df["lead_time"]>=0].reset_index(drop=True)

In [51]:
df.head(1)

,patientid,appointmentid,gender,scheduledday,appointmentday,age,neighbourhood,scholarship,hypertension,diabetes,alcoholism,handcap,sms_received,no_show,lead_time
0,95985133231274.0,5626772,F,2016-04-27 08:36:51+00:00,2016-04-29 00:00:00+00:00,76,REPÚBLICA,0,1,0,0,0,0,No,1